languagepy = {
    '01monthEN': 'jan.',
    '01monthRU': 'янв.',
    '02monthEN': 'feb.',
    '02monthRU': 'фев.',
    '03monthEN': 'mar.',
    '03monthRU': 'мар.',
    '04monthEN': 'apr.',
    '04monthRU': 'апр.',
    '05monthEN': 'may',
    '05monthRU': 'май',
    '06monthEN': 'june',
    '06monthRU': 'июн.',
    '07monthEN': 'july',
    '07monthRU': 'июл.',
    '08monthEN': 'aug.',
    '08monthRU': 'авг.',
    '09monthEN': 'sept.',
    '09monthRU': 'сен.',
    '10monthEN': 'oct.',
    '10monthRU': 'окт.',
    '11monthEN': 'nov.',
    '11monthRU': 'ноя.',
    '12monthEN': 'dec.',
    '12monthRU': 'дек.',
    'aboutcommandEN': 'bot information',
    'aboutcommandRU': 'информация о боте',
    'aboutdescEN': 'Very simple discord bot written on discord.py',
    'aboutdescRU': 'Очень простой дискорд-бот, написанный на discord.py',
    'allUsersEN': 'All: ',
    'allUsersRU': 'Всего: ',
    'amsterdamEN': 'Amsterdam',
    'amsterdamRU': 'Амстердам',
    'animefacepalmEN': '```face-palm gif```',
    'animefacepalmRU': '```гифка с фейспалмом```',
    'animehugEN': '```hug gif```',
    'animehugRU': '```гифка с обнимашками```',
    'animepetEN': '```pat gif```',
    'animepetRU': '```гифка с поглаживанием :3```',
    'animequoteEN': '```Random anime quote```',
    'animequoteRU': '```Рандомная цитата из аниме```',
    'animesadEN': '```sad gif```',
    'animesadRU': '```грустная гифка```',
    'animewinkEN': '```wink gif```',
    'animewinkRU': '```гифка с подмигованием```',
    'avatarhelpEN': 'Shows the users avatar',
    'avatarhelpRU': 'Показывает аватарку пользователя',
    'badRequestEN': 'Bad request: ',
    'badRequestRU': 'Неверный запрос: ',
    'basicInfoEN': 'Basic information: ',
    'basicInfoRU': 'Основная информация: ',
    'botEN': ' bot',
    'botinviteEN': '**Bot invite:**                    ⠀',
    'botinviteRU': '**Приглашение бота:**   ⠀',
    'botnameEN': '**Bot name:**                      ⠀',
    'botnameRU': '**Ник бота:**                      ⠀',
    'botRU': ' бот',
    'botUsersEN': 'Bots: ',
    'botUsersRU': 'Ботов: ',
    'botversionEN': '**Bot version:**                   ⠀',
    'botversionRU': '**Версия бота:**                 ⠀',
    'brazilEN': 'Brazil',
    'brazilRU': 'Бразилия',
    'categoriesEN': '**Categories:**',
    'categoriesRU': '**Категории:**',
    'ChannelsEN': 'Channels:  ⠀',
    'ChannelsRU': 'Каналы:    ⠀',
    'charactherEN': ' Characther:',
    'charactherRU': ' Персонаж:',
    'clickhereEN': '[[Click here]]',
    'clickhereRU': '[[Кликни сюда]]',
    'commandsEN': ' commands',
    'commandsRU': ' комманды',
    'cookiesandteaEN': 'Cookies and tea: ',   
    'cookiesandteaRU': 'Печеньки и чай: ',
    'customactivityEN': '**Custom status: **',
    'customactivityRU': '**Пользовательский статус: **',
    'dndEN': 'Do Not Disturb',
    'dndRU': 'Не беспокоить',
    'do_not_disturbEN': 'Do Not Disturb',
    'do_not_disturbRU': 'Не беспокоить',
    'double_table_flipEN': 'Highest',
    'double_table_flipRU': 'Самый высокий',
    'dubaiEN': 'Dubai',
    'dubaiRU': 'Дубай',
    'ErrNotArgEN': 'Error: No arguments',
    'ErrNotArgRU': 'Ошибка: Нет аргументов',
    'errorEN': 'Error',
    'errorRU': 'Ошибка',
    'eu-centralEN': 'EU central',
    'eu-centralRU': 'Центральная Европа',
    'eu-westEN': 'EU west',
    'eu-westRU': 'Западная Европа',
    'europeEN': 'Europe',
    'europeRU': 'Европа',
    'extremeEN': 'Highest',
    'extremeRU': 'Самый высокий',
    'facepalmEN': 'face-palm',
    'facepalmRU': 'фейспалм',
    'frankfurtEN': 'Frankfurt',
    'frankfurtRU': 'Франкфурт',
    'funcommandsEN': 'Fun commands',
    'funcommandsRU': 'Фановые комманды',
    'funMenuDescEN': '```All commands for fun```',
    'funMenuDescRU': '```Все комманды для фана```',
    'funMenuEN': '**    FUN   **',
    'funMenuRU': '**    ФАН   **',
    'gayEN': 'gay',
    'gayRU': 'гей',
    'guildCreationDateEN': 'Creation date:',
    'guildCreationDateRU': 'Дата создания:  ',
    'guildinfohelpEN': 'Displays server information',
    'guildinfohelpRU': 'Отображает информацию о сервере',
    'helpfunanimeEN': '```Shows anime submenu```',
    'helpfunanimeRU': '```Показывает аниме подменю```',
    'helpfunothersEN': '```Shows others submenu```',
    'helpfunothersRU': '```Показывает подменю с "другим"```',
    'helplistendEN': ' Use the "!= help" for a list of commands',
    'helplistendRU': ' Введите "!= help" для отображения комманд бота',
    'highEN': 'High',
    'highRU': 'Высокий',
    'hongkongEN': 'Hong Kong',
    'hongkongRU': 'Гонконг',
    'hostEN': '**Host:      **                    ⠀',
    'hostRU': '**Хост:      **                    ⠀',
    'hugEN': 'hug',
    'hugRU': 'Обнимашки',
    'idleEN': 'Idle',
    'idleRU': 'Не активен',
    'indiaEN': 'India',
    'indiaRU': 'Индия',
    'infoAboutBotErrEN': 'Error: User is bot',
    'infoAboutBotErrRU': 'Ошибка: Пользователь это бот',
    'infoAboutEN': 'Info about: ',
    'infoAboutRU': 'Информация о: ',
    'invisibleEN': 'Offline',
    'invisibleRU': 'Оффлайн',
    'japanEN': 'Japan',
    'japanRU': 'Япония',
    'libraryEN': '**Library:    **                   ⠀',
    'libraryRU': '**Библиотека:    **          ⠀',
    'listofavalibleEN': 'List of available arguments:',
    'listofavalibleRU': 'Лист допустимых аргументов',
    'londonEN': 'London',
    'londonRU': 'Лондон',
    'lowEN': 'Low',
    'lowRU': 'Низкий',
    'lyricsEN': 'Lyrics:',
    'lyricsRU': 'Текст:',
    'mediumEN': 'Medium',
    'mediumRU': 'Средний',
    'noneEN': 'None',
    'noneRU': 'Отсутсвует',
    'NoResultErrorMessageEN': 'Sorry, there are no Wikifur articles with this title. Please try "!= wikifur_search (your request)" to look up Wikifur article names',
    'NoResultErrorMessageRU': 'К сожалению, в Викифур нет статей с таким названием. Попробуйте "!= Wikifur_search (ваш запрос)", чтобы найти название статьи в Викифур',
    'NoSearchresultsEN': 'Sorry, there are no search results for ',
    'NoSearchresultsRU': 'Извините, нет результатов поиска по запросу ',
    'notFoundEN': 'Not found: ',
    'notFoundRU': 'Не найдено: ',
    'NotSpecificRequestErrorMessageEN': 'Sorry, your search request wasnt specific enough. Please try "!= wikifur_search (your request)". This will display all wikifur articles with your search request.',
    'NotSpecificRequestErrorMessageRU': 'К сожалению, ваш поисковый запрос недостаточно конкретен. Пожалуйста, попробуйте "!= Wikifur_search (ваш запрос)". Это отобразит все статьи викифур с вашим поисковым запросом.',
    'offlineEN': 'Offline',
    'offlineRU': 'Оффлайн',
    'ohnoEN': 'OH NO. ',
    'ohnoRU': 'О НЕТ. ',
    'onlineEN': 'Online',
    'onlineRU': 'В сети',
    'othersLyricsEN': '```Shows the song lyrics```',
    'othersLyricsRU': '```Показывает текст песни```',
    'othersMemeEN': '```Shows an unfunny meme```',
    'othersMemeRU': '```Показывает несмешной мем```',
    'othersMinecraftEN': '```Shows nickname, uuid and minecraft skin```',
    'othersMinecraftRU': '```Показывает ник, uuid и скин minecraft```',
    'ownerEN': '**Owner:      **                   ⠀',
    'ownerRU': '**Автор:      **                   ⠀',
    'patEN': 'pat',
    'patRU': 'гифка с поглаживанием',
    'prefixEN': '**Prefix:      **                  ⠀',
    'prefixRU': '**Префикс:      **                 ⠀',
    'quoteEN': 'quote',
    'quoteRU': ' цитата',
    'randomErrEN': 'Sorry, a random error occurred. Please try again.',
    'randomErrRU': 'Извините, произошла неизвестная ошибка. Пожалуйста, попробуйте еще раз.',
    'randommemeEN': 'Random meme',
    'randommemeRU': 'Рандомный мем',
    'readFurtherEN': '[Read further]',
    'readFurtherRU': '[Читать дальше]',
    'realUsersEN': 'Users: ',
    'realUsersRU': 'Людей: ',
    'russiaEN': 'Russia',
    'russiaRU': 'Россия',
    'sadEN': 'sad gif',
    'sadRU': 'грустная гифка',
    'serverInfoOwnerEN': 'Owner:   ',
    'serverInfoOwnerRU': 'Владелец:',
    'serverInfoRegionEN': 'Server region: ',
    'serverInfoRegionRU': 'Регион сервера:',
    'serverOwnerEN': 'Owner: ',
    'serverOwnerRU': 'Владелец:',
    'serverWordEN': ' server',
    'serverWordRU': ' сервер',
    'setlangEN': 'Sets the language for the bot',
    'setlangRU': 'Устанавливает язык для бота',
    'settingscommandsEN': 'Settings commands',
    'settingscommandsRU': 'Комманды для настройки',
    'settingsMenuDescEN': '```Bot settings and more```',
    'settingsMenuDescRU': '```Настройки бота и другое```',
    'settingsMenuEN': '**    UTILITIES   **',
    'settingsMenuRU': '**     УТИЛИТЫ    **',
    'singaporeEN': 'Singapore',
    'singaporeRU': 'Сингапур',
    'south-koreaEN': 'South korea',
    'south-koreaRU': 'Южная Корея',
    'southafricaEN': 'South africa',
    'southafricaRU': 'Южная Африка',
    'supportserverEN': '**Support server:**             ⠀',
    'supportserverRU': '**Сервер поддержки:**   ⠀',
    'sydneyEN': 'Sydney',
    'sydneyRU': 'Сидней',
    'table_flipEN': 'High',
    'table_flipRU': 'Высокий',
    'testEN': 'test',
    'testRU': 'тест',
    'TextChannelsEN': 'Text: ',
    'TextChannelsRU': 'Текстовые: ',
    'totalguildsEN': '**Total guilds:    **              ⠀',
    'totalguildsRU': '**Всего серверов:    **       ⠀',
    'unkargEN': 'Unknown argument.',
    'unkargRU': 'Недопустимый аргумент',
    'unkownerrorEN': 'Error: Unknown error',
    'unkownerrorRU': 'Ошибка: Неизвестная ошибка',
    'us-centralEN': 'US central',
    'us-centralRU': 'Центральные СШ',
    'us-eastEN': 'US east',
    'us-eastRU': 'Восточные СШ',
    'us-southEN': 'US south',
    'us-southRU': 'Южные СШ',
    'us-westEN': 'US west',
    'us-westRU': 'Западные СШ',
    'usedEN': 'Used:',
    'usedRU': 'Использовалось:',
    'userActivityNoneEN': 'none ',
    'userActivityNoneRU': 'нет ',
    'userAvatarEN': 'Avatar ',
    'userAvatarRU': 'Аватар ',
    'userinfoAccCreatedEN': '**Created: **',
    'userinfoAccCreatedRU': '**Регистрация аккаунта: **',
    'userinfohelpEN': 'Displays information about the user',
    'userinfohelpRU': 'Отображает информацию о пользователе',
    'userinfoJoinedEN': '**Joined: **',
    'userinfoJoinedRU': '**Присоединился: **',
    'userinfoStatusEN': '**Status: **',
    'userinfoStatusRU': '**Статус: **',
    'userInfoUsernameEN': '**Username: **',
    'userInfoUsernameRU': '**Ник: **',
    'usernameEN': 'Username: ',
    'usernameRU': 'Ник: ',
    'usersNametagEN': 'Users:                ⠀',
    'usersNametagRU': 'Пользователи:         ⠀',
    'userStatusSpotifyEN': 'Listening to  ',
    'userStatusSpotifyRU': 'Слушает ',
    'VerificationLevelEN': 'Verification Level:',
    'VerificationLevelRU': 'Уровень Проверки:  ',
    'very_highEN': 'Highest',
    'very_highRU': 'Самый высокий',
    'vip-amsterdamEN': 'Amsterdam VIP',
    'vip-amsterdamRU': 'Амстердам VIP',
    'vip-us-eastEN': 'US east VIP',
    'vip-us-eastRU': 'Восточные Соединенные Штаты VIP',
    'vip-us-westEN': 'US west VIP',
    'vip-us-westRU': 'ападные Соединенные Штаты VIP',
    'VoiceChannelsEN': 'Voice: ',
    'VoiceChannelsRU': 'Голосовые: ',
    'wikiFsearchresultsEN': 'Wikifur search results:',
    'wikiFsearchresultsRU': 'Результаты поиска в Wikifur:',
    'wikifurcommandsEN': 'Wikifur commands',
    'wikifurcommandsRU': 'Викифур комманды',
    'wikifurDisplayInfoEN': '```Display info from wikifur pages```',
    'wikifurDisplayInfoRU': '```Отображение информации со страниц викифур```',
    'wikifurMenudescEN': '```All wikifur commands```',
    'wikifurMenudescRU': '```Все комманды для викифура```',
    'wikifurMenuEN': '**    WIKIFUR   **',
    'wikifurMenuRU': '**    ВИКИФУР   **',
    'wikifurRandomInfoEN': '```Display random wiki from wikifur```',
    'wikifurRandomInfoRU': '```Показывает случайную вики из викифура```',
    'wikifurSearchInfoEN': '```Searching wikis in Wikifur```',
    'wikifurSearchInfoRU': '```Поиск вики в Викифур```',
    'winkEN': 'wink',
    'winkRU': 'подмигивание', 
    'yearEN': '',
    'yearRU': ' г.', 
    'pingEN': 'Ping:',
    'pingRU': 'Пинг:', 
    'msEN': ' ms.',
    'msRU': ' мс.', 
    'cookiesPlusEN': 'You baked ',
    'cookiesPlusRU': 'Вы приготовили ', 
    'cookiestwoEN': ' cookies  🍪',
    'cookiestwoRU': ' печенек 🍪', 
    'cookiesEN': 'Сookies  🍪',
    'cookiesRU': 'Gеченьки 🍪', 
}